name: Checkmarx Scheduled Scan
on:
  schedule:
    - cron: '30 2 * * 2,4' # the cron run on UTC so tis will run on 8am IST on Tuesday and Thursday

jobs:
  checkmarx_schedule:
    if: (github.repository == 'intel-innersource/applications.web.mydeals.webui')
    runs-on: [self-hosted,mydeals-runner01]
    steps:
        - name: Checkmarx schedule
          run: |
             node C:\automation_newman\checkmarx.js